<a href="https://colab.research.google.com/github/SilahicAmil/30-Days-Of-ML/blob/main/Day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to NumPy

In [1]:
import numpy as np

## Arrays

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [5]:
# 2 Dimensional Array
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Arange

Returns evenly spaced values within given intervals


In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# Start, End, Step Size
# 1- Dimensional
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### Linspace

Returns evenly spaced nuymbers over a specified interval

Linspace takes 3rd argument of number of points you want

In [19]:
# 1-Dimensional
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

# Random

numpy has many ways to create random number arrays

## Rand

Creates an array of the given shape and populates it with random numbers in a uniform way

In [25]:
np.random.rand(6)

array([0.20663686, 0.39467877, 0.75955182, 0.66479336, 0.82376072,
       0.00488029])

In [26]:
np.random.rand(10,5)

array([[0.81639034, 0.37855208, 0.04630609, 0.87393626, 0.16040233],
       [0.63809153, 0.76316366, 0.37803424, 0.21315691, 0.57312977],
       [0.38570878, 0.17784802, 0.58337415, 0.62162425, 0.22761127],
       [0.5809603 , 0.48354232, 0.5965865 , 0.25745063, 0.74462448],
       [0.04882787, 0.7559743 , 0.472965  , 0.00630942, 0.29917297],
       [0.1315032 , 0.58545207, 0.25771159, 0.02399361, 0.93871628],
       [0.71982429, 0.45219244, 0.54152605, 0.40785587, 0.39231677],
       [0.53222521, 0.6655872 , 0.11419404, 0.28685806, 0.18153815],
       [0.46437185, 0.88345213, 0.59534058, 0.10440513, 0.14933616],
       [0.16209899, 0.32735753, 0.75836432, 0.93650057, 0.86243049]])

## Randn

Returns numbers from the standard distribution

In [28]:
np.random.randn(5)

array([-0.7603059 , -0.46481136,  0.37354444,  1.89409636,  0.18810711])

In [29]:
# 2-Dimensional
np.random.randn(1,15)

array([[ 0.08118153, -0.95273362,  0.70839066, -0.02698287,  0.51618497,
        -1.79522913,  1.06304277,  0.33923634, -0.72751995, -0.17527568,
        -1.03983513, -0.32098159,  1.27363861, -0.79468212,  0.32927983]])

## Randint

Returns random integers from low to high

In [30]:
np.random.randint(50,600)

462

In [32]:

np.random.randint(1,100,10)

array([90, 84, 98, 89, 97, 29, 74,  1, 16, 27])

# Attributes and Methods


In [33]:
arr = np.arange(25)
rand_arr = np.random.randint(0,50,5)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
rand_arr

array([15, 19,  3, 10, 21])

# Reshape

Returns and array containg the same data with a different shape

In [38]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Max, Min, Argmax, Argmin

These are useful methods for finding max or min values and indexing

In [40]:
rand_arr

array([15, 19,  3, 10, 21])

In [41]:
rand_arr.max()

21

In [42]:
rand_arr.argmax()


4

In [43]:
rand_arr.min()

3

In [45]:
rand_arr.argmin()

2

# Shape

Shape is an attribute not a method

In [47]:
arr.shape


(25,)

In [53]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [54]:
arr.reshape(1,25).shape

(1, 25)

In [55]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [56]:
arr.reshape(25,1).shape

(25, 1)

# Dtype

Grabbing the Dtype is like grabbing its purpose. Whether it be int, objects, time values and etc

In [59]:
rand_arr.dtype

dtype('int64')